In [91]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt
import math

In [92]:

df=pd.read_csv("hiring.txt")

In [93]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [94]:
df1=df.to_csv("hiring.csv",index=False)
df1=pd.read_csv("hiring.csv")

In [95]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [96]:
df1.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [97]:
df1.columns=['experience','test_score','interview_score','salary']

In [98]:
df1.columns

Index(['experience', 'test_score', 'interview_score', 'salary'], dtype='object')

In [99]:
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [100]:
df1_median=math.floor(df1.test_score.median())

In [101]:
df1_median

8

In [102]:
df1.test_score=df1.test_score.fillna(df1_median)
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [103]:
df1.experience=df1.experience.fillna('zero')

In [104]:
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [105]:
df1.experience=['0','0','5','2','7','3','10','11']


In [106]:
df1

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         8.0                7   72000
7         11         7.0                8   80000

In [107]:
from sklearn import linear_model

In [108]:
reg=linear_model.LinearRegression()
reg.fit(df1[['experience','test_score','interview_score']],df1.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [109]:
reg.intercept_

17737.26346433771

In [110]:
reg.coef_

array([ 2812.95487627,  1845.70596798,  2205.24017467])

In [111]:
reg.predict([[2,9,6]])

array([ 53205.96797671])

In [112]:
reg.predict([[12,10,10]])

array([ 92002.18340611])