## In this exercise we are going to predict iris flower based on features which are sepal length in cm,sepal width in cm,petal length in cm,petal width in cm
## our tast is to predict whether flower is  Iris-Setosa or Iris-Versicolour or Iris-Virginica
## 0=Iris-Setosa
## 1=Iris-Versicolour
## 2=Iris-Virginica

In [35]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import datasets

In [36]:
iris=datasets.load_iris()

In [37]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [38]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [39]:
features=iris.data
labels=iris.target

In [40]:
features[0:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [41]:
labels[0:5]

array([0, 0, 0, 0, 0])

In [42]:
Logistic_reg=LogisticRegression()
Logistic_reg.fit(features,labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [43]:
Logistic_reg.predict([[1,2,3,4]]) #This is virginica

array([2])

In [44]:
Logistic_reg.predict([[5.1,  3.5,  1.4,  0.2]])  #This is  setosa

array([0])

In [45]:
Logistic_reg.score(features,labels) #our model accuracy is 95%

0.95999999999999996